org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true
org.gradle.caching = true

mod_version = 2.5.2

minecraft_version = 1.16.1
# https://github.com/tildejustin/yarn/tags
yarn_mappings = 1.16.1-build.28
loader_version = 0.16.9
target_version = 1.16.1
# https://jitpack.io/#kingcontaria/speedrunapi
speedrunapi_version = 96811e85e8
archives_name = sodium
maven_group = me.jellysquid.mods
