# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=21w03a
yarn_mappings=21w03a+build.38
loader_version=0.14.21
fabric_version=0.36.1+1.17

# Mod Properties
mod_version=0.3.3
maven_group=me.jellysquid.mods
archives_base_name=sodium-fabric
